# Generated by Django 5.2.5 on 2025-08-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
