# Generated by Django 5.2.5 on 2025-08-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_status_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reference_to',
            new_name='assignee',
        ),
    ]
